# Generated by Django 5.1.3 on 2024-11-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('p_stock', models.FloatField()),
                ('s_stock', models.FloatField()),
                ('d_stock', models.FloatField()),
                ('t_stock', models.FloatField()),
                ('ps_stock', models.FloatField()),
                ('ss_stock', models.FloatField()),
                ('dcsale_stock', models.IntegerField()),
                ('closing_stock', models.DecimalField(decimal_places=2, max_digits=15)),
                ('container', models.DecimalField(decimal_places=2, max_digits=15)),
                ('disc', models.DecimalField(decimal_places=2, max_digits=15)),
                ('selling_price', models.FloatField()),
                ('mrp', models.FloatField()),
                ('tax', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tax_two', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tax_three', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cess', models.DecimalField(decimal_places=2, max_digits=4)),
                ('priority', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('hsn_no', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('enable', models.IntegerField()),
                ('stock_alert', models.IntegerField()),
                ('itemdetails', models.CharField(max_length=500)),
                ('ext1', models.CharField(blank=True, max_length=100, null=True)),
                ('ext2', models.CharField(blank=True, max_length=100, null=True)),
                ('ext3', models.CharField(blank=True, max_length=100, null=True)),
                ('ext4', models.CharField(blank=True, max_length=100, null=True)),
                ('ext5', models.CharField(blank=True, max_length=100, null=True)),
                ('ext6', models.CharField(blank=True, max_length=100, null=True)),
                ('ext7', models.CharField(blank=True, max_length=100, null=True)),
                ('ext8', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, max_length=250, null=True)),
                ('to_id', models.IntegerField()),
                ('dealer_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
