# Generated by Django 5.1.3 on 2024-11-07 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eSeveTickets', '0002_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('currency_symbol', models.CharField(choices=[('₹', '₹ (Rupee)'), ('$', '$(Dollar)')], max_length=2)),
                ('maintain', models.CharField(choices=[('Accounts', 'Accounts'), ('Inventory', 'Inventory')], max_length=10)),
                ('financial_year', models.CharField(max_length=20)),
                ('gstin', models.CharField(max_length=15)),
                ('st', models.CharField(max_length=10)),
                ('pan', models.CharField(max_length=10)),
                ('cin_llp', models.CharField(max_length=20)),
                ('serial_option', models.CharField(choices=[('General Accounts / Billing', 'General Accounts / Billing'), ('Without Serials', 'Without Serials'), ('With Serials', 'With Serials')], max_length=30)),
                ('purchase_date', models.DateField()),
                ('sales_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eSeveTickets.state')),
            ],
        ),
    ]
